language: go
git: 
  depth: 50
sudo: required
install:
  - curl https://get.dgraph.io -sSf | bash
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
before_script:
  - dgraph zero &
  - ZERO_PID=$!
  - dgraph server --lru_mb 1024 &
  - SERVER_PID=$!
script:
  - go test
after_script:
  - kill -2 $SERVER_PID
  - kill -2 $ZERO_PID